version: '3'
services:
  nextjs:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      
    networks:
      - mas-hms-network

networks:
  mas-hms-network:
    external: true   


