import { IAdmissionInitialData } from "../order/initialDataAndTypes";

export const religions = ["Islam", "Hindu", "Cristian", "Buddhi"];

export const bangladeshDistricts = [
  "Bagerhat",
  "Bandarban",
  "Barguna",
  "Barisal",
  "Bhola",
  "Bogra",
  "Brahmanbaria",
  "Chandpur",
  "Chapai Nawabganj",
  "Chattogram",
  "Chuadanga",
  "Comilla",
  "Cox's Bazar",
  "Dhaka",
  "Dinajpur",
  "Faridpur",
  "Feni",
  "Gaibandha",
  "Gazipur",
  "Gopalganj",
  "Habiganj",
  "Jamalpur",
  "Jashore",
  "Jhalokathi",
  "Jhenaidah",
  "Joypurhat",
  "Khagrachari",
  "Khulna",
  "Kishoreganj",
  "Kurigram",
  "Kushtia",
  "Lakshmipur",
  "Lalmonirhat",
  "Madaripur",
  "Magura",
  "Manikganj",
  "Meherpur",
  "Moulvibazar",
  "Munshiganj",
  "Mymensingh",
  "Naogaon",
  "Narail",
  "Narayanganj",
  "Narsingdi",
  "Natore",
  "Netrokona",
  "Nilphamari",
  "Noakhali",
  "Pabna",
  "Panchagarh",
  "Patuakhali",
  "Pirojpur",
  "Rajbari",
  "Rajshahi",
  "Rangamati",
  "Rangpur",
  "Satkhira",
  "Shariatpur",
  "Sherpur",
  "Sirajganj",
  "Sunamganj",
  "Sylhet",
  "Tangail",
  "Thakurgaon",
];

export const aInitialData: IAdmissionInitialData = {
  totalAmount: 0,
  parcentDiscount: 0,
  cashDiscount: 0,
  vat: 0,
  paid: 0,

  discountedBy: "system",
  patientType: "notRegistered",
  regNo: "",
  name: "",
  gender: "",
  fatherName: "",
  presentAddress: "",
  permanentAddress: "",
  age: "",
  bloodGroup: "",
  status: "admitted",
  admissionDate: "",
  admissionTime: "",
  assignDoct: undefined,
  refDoct: undefined,
  releaseDate: "",

  maritalStatus: "",

  occupation: "",
  education: "",
  district: "",
  religion: "",
  residence: "",
  citizenShip: "",
  disease: "",
  isTransfer: false,
  allocatedBed: undefined,
  worldId: "",
  isFixed: false,
  // deliveryTime: new Date(),
};
